version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - ./.env
    restart: always
    ports:
      - "4000:3000"
    networks:
      - backend
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - "8081:80"

  postgres:
    container_name: my_database
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/postgres/
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend: